import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {/* 링크 컴포넌트 로딩 시에 prefetch를 사용하여 미리 로딩 */}
          <Link href="/hello">Go Hello</Link> | <Link href="/">Go Index</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
